import { dirname, join } from "node:path";
import { homedir } from "node:os";
import { execFileSync } from "node:child_process";
import { LAUNCHD_LABEL } from "@lobster-farm/shared";

// Binaries the daemon ecosystem needs available in PATH.
const DETECTED_BINARIES = ["bun", "node", "claude", "git", "gh", "tmux", "op"] as const;

// Base directories always included in PATH (standard macOS locations).
const BASE_PATH_DIRS = ["/opt/homebrew/bin", "/usr/local/bin", "/usr/bin", "/bin"] as const;

// Env vars captured from the current environment into env.sh.
const CAPTURED_ENV_VARS = ["BUN_INSTALL", "OP_SERVICE_ACCOUNT_TOKEN"] as const;

/**
 * Escape a value for safe interpolation inside double-quoted shell strings.
 * Handles backslashes, double quotes, backticks, and dollar signs.
 */
function escape_shell_value(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$");
}

/**
 * Resolve the absolute path of a binary using `which`.
 * Returns the path, or null if not found.
 */
function resolve_binary(name: string): string | null {
  try {
    return execFileSync("which", [name], {
      encoding: "utf-8",
      env: process.env,
      stdio: ["ignore", "pipe", "ignore"],
    }).trim() || null;
  } catch {
    return null;
  }
}

/**
 * Detect binary directories and environment variables, then generate the
 * contents of env.sh — the daemon's environment configuration file.
 *
 * Pure function (aside from process.env reads) for testability. Pass `env`
 * and `binary_resolver` to override for tests.
 */
export function generate_env_sh(
  env: Record<string, string | undefined> = process.env,
  binary_resolver: (name: string) => string | null = resolve_binary,
): string {
  // Collect PATH directories from detected binaries
  const detected_dirs: string[] = [];
  const binary_comments: string[] = [];

  for (const bin of DETECTED_BINARIES) {
    const path = binary_resolver(bin);
    if (path) {
      const dir = dirname(path);
      if (!detected_dirs.includes(dir)) {
        detected_dirs.push(dir);
      }
      binary_comments.push(`# ${bin}: ${path}`);
    } else {
      binary_comments.push(`# ${bin}: not found`);
    }
  }

  // Build deduplicated PATH: detected dirs first, then base dirs
  const all_dirs = [...detected_dirs];
  for (const base of BASE_PATH_DIRS) {
    if (!all_dirs.includes(base)) {
      all_dirs.push(base);
    }
  }
  const path_value = all_dirs.join(":");

  // Build env var exports
  const env_exports: string[] = [];
  for (const key of CAPTURED_ENV_VARS) {
    const value = env[key];
    if (value) {
      env_exports.push(`export ${key}="${escape_shell_value(value)}"`);
    }
  }

  const env_section = env_exports.length > 0
    ? `\n# Environment variables (captured at generation time)\n${env_exports.join("\n")}\n`
    : "";

  return `#!/bin/zsh
# LobsterFarm daemon environment — auto-generated by \`lf start\`
# Edit this file to add tools or env vars the daemon needs.
# Re-run \`lf start\` after deleting to regenerate from scratch.

# Detected binaries:
${binary_comments.join("\n")}

export PATH="${path_value}"
${env_section}`;
}

/**
 * Generate the contents of the wrapper script that sources env.sh
 * and exec's the daemon.
 *
 * @param node_path   Absolute path to the node binary.
 * @param daemon_path Absolute path to the daemon entry point (index.js).
 */
export function generate_wrapper_sh(node_path: string, daemon_path: string): string {
  const home = homedir();
  return `#!/bin/zsh
# LobsterFarm daemon wrapper — managed by \`lf start\`, do not edit.
# Sources env.sh for PATH and secrets, then exec's the daemon.

ENV_FILE="${home}/.lobsterfarm/env.sh"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "[start-daemon] FATAL: $ENV_FILE not found." >&2
  echo "[start-daemon] Run \`lf start\` to regenerate it." >&2
  exit 1
fi

source "$ENV_FILE"
exec "${node_path}" "${daemon_path}"
`;
}

/**
 * Generate a macOS launchd plist XML string for the LobsterFarm daemon.
 *
 * The plist delegates all environment setup to the wrapper script —
 * no EnvironmentVariables section is needed.
 */
export function generate_plist(
  wrapper_path: string,
  log_path: string,
  working_dir: string,
): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${wrapper_path}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${working_dir}</string>
  <key>StandardOutPath</key>
  <string>${log_path}</string>
  <key>StandardErrorPath</key>
  <string>${log_path}</string>
  <key>KeepAlive</key>
  <true/>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>`;
}

/** Return the standard path for the LobsterFarm launchd plist. */
export function plist_path(): string {
  return join(homedir(), "Library", "LaunchAgents", `${LAUNCHD_LABEL}.plist`);
}

/** Load the LobsterFarm service via launchctl. */
export async function load_service(): Promise<void> {
  const { exec_command } = await import("./process.js");
  const uid = process.getuid?.() ?? 501;
  const { exitCode, stderr } = await exec_command(
    `launchctl bootstrap gui/${uid} "${plist_path()}"`,
  );
  if (exitCode !== 0 && !stderr.includes("already bootstrapped")) {
    throw new Error(`Failed to load service: ${stderr.trim()}`);
  }
}

/** Unload the LobsterFarm service via launchctl. */
export async function unload_service(): Promise<void> {
  const { exec_command } = await import("./process.js");
  const uid = process.getuid?.() ?? 501;
  const { exitCode, stderr } = await exec_command(
    `launchctl bootout gui/${uid}/${LAUNCHD_LABEL}`,
  );
  if (exitCode !== 0 && !stderr.includes("not find")) {
    throw new Error(`Failed to unload service: ${stderr.trim()}`);
  }
}

/** Check if the LobsterFarm service is currently loaded in launchctl. */
export async function is_service_loaded(): Promise<boolean> {
  const { exec_command } = await import("./process.js");
  const uid = process.getuid?.() ?? 501;
  const { exitCode } = await exec_command(
    `launchctl print gui/${uid}/${LAUNCHD_LABEL} 2>/dev/null`,
  );
  return exitCode === 0;
}
